# Generated by Django 3.2.4 on 2021-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('generic', 'GENERIC'), ('python', 'PYTHON'), ('javascript', 'JAVASCRIPT')], default='generic', max_length=10),
        ),
    ]
