# Generated by Django 3.2.4 on 2021-06-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=900),
        ),
    ]
